### ISSUE TITLE
在linux下使用有异常

### ISSUE THREAD

**Issue by osdream** [ecomfe/edp-bcs#2]
/node_modules/edp/node_modules/edp-bcs/lib/sdk.js:67
     [exec]             if (version.indexOf('Nahant Update 3') != -1) {
     [exec]                         ^
     [exec] TypeError: Object Red Hat Enterprise Linux AS release 4 (Nahant Update 3)
     [exec]  has no method 'indexOf'

**Comment by leeight** [comment]
貌似早就修复了，可能用的版本比较老。
